# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Non-Linear Inequality Constraints
#'
#' @details This function evaluates the left-hand side of the constraints
#' \enumerate{
#'   \item \eqn{-(\alpha + \gamma) \le 0} and
#'   \item \eqn{\frac{1}{n} \sum_{t=1}^{n} \log \Lambda_{t} \left( \theta \right) + \delta.}
#'  }
#'
#' @param y numeric vector of observations \eqn{y_0, y_1, ...}
#' @param theta numeric vector of parameter values
#'
#' @returns Returns a list that contains the value of the left-hand side
#' (`"objective"`) of each constraint and the Jacobian ("jacobian") of the
#' constraint.
#'
cnstr <- function(y, theta) {
    .Call(`_betatgarch_cnstr`, y, theta)
}

#' Beta-t-GARCH Recursion/Filter
#'
#' @details
#'   Calculates the values of
#'   \itemize{
#'     \item each observation's contribution to the log-likelihood,
#'     \item the conditional variance,
#'     \item score innovation/residual and
#'     \item model residuals.
#'   }
#'
#' @param y numeric vector of observations \eqn{y_0, y_1, ...}
#' @param f_0 initial value of the conditional variance
#' @param theta numeric vector of parameter values
#'
#' @returns
#'   Returns a list of vectors. The elements of the list are (in order):
#'   \enumerate{
#'     \item each observation's contribution to the log-likelihood (`"llik_t"`),
#'     \item the conditional variances (`"f"`),
#'     \item score residuals (`"s_t"`) and
#'     \item model residuals (`"residuals"`).
#'   }
#'
recursion_lst <- function(y, f_0, theta) {
    .Call(`_betatgarch_recursion_lst`, y, f_0, theta)
}

#' Negative log-likelihood and its gradient.
#'
#' @details
#'   Calculates the negative log-likelihood of the Beta-GARCH(1, 1) model
#'   with leverage and its gradient w.r.t. to vector of parameters.
#'
#' @param y numeric vector of observations \eqn{y_0, y_1, ...}
#' @param f_0 initial value of the conditional variance
#' @param theta numeric vector of parameter values
#'
#' @returns
#'   Returns a list that contains the negative log-likelihood (`"objective"`)
#'   and the gradient (`"gradient"`) of the negative log-likelihood w.r.t. the
#'   model parameters.
#'
nll <- function(y, f_0, theta) {
    .Call(`_betatgarch_nll`, y, f_0, theta)
}

#' Simulate Values From Beta-t-GARCH Model Given a Vector of Innovations
#'
#' @details Simulates observations from a Beta-t-GARCH model.
#'
#' @param e numeric vector of zero-mean and unit-variance innovations
#' @param f_0 initial value of the conditional variance
#' @param theta numeric vector of parameter values
#'
#' @returns
#'   Returns a list of vectors. The elements of the list are (in order):
#'   \itemize{
#'    \item the simulated observations (`"y_t"`),
#'    \item the conditional variance (`"f_t"`),
#'    \item score innovations (`"s_t"`),
#'    \item the contributions to the log-likelihood (`"llik_t"`) and
#'    \item the original series of innovations (`"innovations"`).
#'   }
#'
simulate_lst <- function(e, f_0, theta) {
    .Call(`_betatgarch_simulate_lst`, e, f_0, theta)
}

